name: Setup pnpm
description: Setup pnpm using the version pinned in package.json's volta section

runs:
  using: composite
  steps:
    - id: package-json
      shell: bash
      run: |
        {
          echo "package-json<<EOF"
          cat package.json
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - shell: bash
      run: |
        echo "PNPM_VERSION=${{ fromJson(steps.package-json.outputs.package-json).volta.pnpm }}" >> $GITHUB_ENV

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
