name: Update Waypoint ECS service to add EFS mount
description: "Add EFS mount to ECS service created by Waypoint"
inputs:
  app:
    description: "Name of the waypoint app"
    required: true
  project:
    description: "The project the app belongs to"
    required: false
    default: "cardstack"
  config:
    description: "Configuration for EFS volumes"
    required: true
  waypoint-hcl:
    description: "Path to the waypoint.hcl file"
    required: false
    default: "waypoint.hcl"
runs:
  using: "node16"
  main: "dist/index.js"
