name: Add autoscaling to ECS service
description: "Add autoscaling to ECS service"
inputs:
  app:
    description: "Name of the waypoint app"
    required: true
  project:
    description: "The project the app belongs to"
    required: false
    default: "cardstack"
  min:
    description: "Minimum value to scale to"
    required: true
  max:
    description: "Maximum value to scale to"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
