name: Waypoint wait ECS service stable
description: "Wait for ECS service to stabilize and ELB target group to be healthy"
inputs:
  app:
    description: "Name of the waypoint app"
    required: true
  project:
    description: "The project the app belongs to"
    required: false
    default: "cardstack"
  waypoint-hcl:
    description: "Path to the waypoint.hcl file"
    required: false
    default: "waypoint.hcl"
runs:
  using: "node16"
  main: "dist/index.js"
