name: Waypoint Build

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      waypoint_version:
        required: false
        default: "0.11.3"
        type: string
      environment:
        required: true
        type: string
      restore-mtime:
        required: false
        type: boolean
        default: false
      working-directory:
        required: false
        type: string
        default: "."

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ ! inputs.restore-mtime }}

      # for certain packages that requires timestamp during their build step
      # https://github.com/cardstack/boxel/pull/276
      - uses: actions/checkout@v3
        if: ${{ inputs.restore-mtime }}
        with:
          fetch-depth: 0

      - uses: chetan/git-restore-mtime-action@v2
        if: ${{ inputs.restore-mtime }}

      - name: Init
        uses: ./.github/actions/init

      - name: Set up env
        shell: bash
        env:
          INPUT_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          if [ "$INPUT_ENVIRONMENT" = "production" ]; then
            echo "AWS_ROLE_ARN=arn:aws:iam::120317779495:role/waypoint" >> $GITHUB_ENV
            echo "WAYPOINT_SERVER_ADDR=${{ secrets.PRODUCTION_WAYPOINT_SERVER_ADDR }}" >> $GITHUB_ENV
            echo "WAYPOINT_SERVER_TOKEN=${{ secrets.PRODUCTION_WAYPOINT_SERVER_TOKEN }}" >> $GITHUB_ENV
            cp waypoint.prod.hcl waypoint.hcl
          elif [ "$INPUT_ENVIRONMENT" = "staging" ]; then
            echo "AWS_ROLE_ARN=arn:aws:iam::680542703984:role/waypoint" >> $GITHUB_ENV
            echo "WAYPOINT_SERVER_ADDR=${{ secrets.STAGING_WAYPOINT_SERVER_ADDR }}" >> $GITHUB_ENV
            echo "WAYPOINT_SERVER_TOKEN=${{ secrets.STAGING_WAYPOINT_SERVER_TOKEN }}" >> $GITHUB_ENV
          else
            echo "unrecognized environment"
            exit 1;
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - uses: lucasmelin/setup-waypoint@v1
        with:
          version: ${{ inputs.waypoint_version }}

      - name: Build app
        run: waypoint build -app=${{ inputs.app }} -plain -push
        working-directory: ${{ inputs.working-directory }}
        env:
          WAYPOINT_SERVER_TLS: "1"
